//! Protocol freeze tests — lock the v1.0 schema hashes, refusal code set,
//! and manifest fingerprint as stable golden values.
//!
//! If any of these tests fail, it means the protocol contract has changed.
//! Any such change must be intentional and require a protocol version bump.
//!
//! Golden values were generated by running:
//!   cargo run --bin postcad-cli -- protocol-manifest --json

use postcad_cli::{
    build_manifest, compute_proof_schema_hash, compute_receipt_schema_hash, is_known_refusal_code,
    refusal_code_set_hash, verifier::VerificationFailure, POSTCAD_PROTOCOL_VERSION, REFUSAL_CODES,
};

// ── Frozen golden hash values (v1.0) ─────────────────────────────────────────

const GOLDEN_RECEIPT_SCHEMA_HASH: &str =
    "37a025b6cb167fbec020d6ea5e64ac9fcc2da7ca9e7aa5bf28272f3114c9fb49";
const GOLDEN_PROOF_SCHEMA_HASH: &str =
    "ebd5a82f9e64d3151d0e2df43585f244abaae664213a9df46a633277b52507e4";
const GOLDEN_REFUSAL_CODE_SET_HASH: &str =
    "4ebf952c33509c9d67850dbd4e43a2fe9a8b0174f4d3009f5c247a4928cb50df";
const GOLDEN_MANIFEST_FINGERPRINT: &str =
    "a46b5519ef5b4e3eda3e24666ec52442be6faa0853fd898ed6a8d1dae34df0fa";

// ── Schema hash stability ─────────────────────────────────────────────────────

/// The receipt schema hash must equal the frozen golden value.
/// Any change to COMMITTED_RECEIPT_FIELDS will break this test.
#[test]
fn receipt_schema_hash_stable() {
    let hash = compute_receipt_schema_hash();
    assert_eq!(
        hash, GOLDEN_RECEIPT_SCHEMA_HASH,
        "receipt_schema_hash changed — update the golden value and bump the protocol version"
    );
}

/// The proof schema hash must equal the frozen golden value.
/// Any change to PROOF_FIELDS will break this test.
#[test]
fn proof_schema_hash_stable() {
    let hash = compute_proof_schema_hash();
    assert_eq!(
        hash, GOLDEN_PROOF_SCHEMA_HASH,
        "proof_schema_hash changed — update the golden value and bump the protocol version"
    );
}

/// The refusal code set hash must equal the frozen golden value.
/// Any change to REFUSAL_CODES will break this test.
#[test]
fn refusal_code_set_hash_stable() {
    let hash = refusal_code_set_hash();
    assert_eq!(
        hash, GOLDEN_REFUSAL_CODE_SET_HASH,
        "refusal_code_set_hash changed — update the golden value and bump the protocol version"
    );
}

/// The manifest fingerprint must equal the frozen golden value.
/// Any change to protocol_version, routing_kernel_version, or any of the
/// three schema hashes will break this test.
#[test]
fn protocol_manifest_fingerprint_stable() {
    let manifest = build_manifest();
    assert_eq!(
        manifest.manifest_fingerprint, GOLDEN_MANIFEST_FINGERPRINT,
        "manifest_fingerprint changed — update the golden value and bump the protocol version"
    );
    // Also verify the component hashes embedded in the manifest.
    assert_eq!(manifest.receipt_schema_hash, GOLDEN_RECEIPT_SCHEMA_HASH);
    assert_eq!(manifest.proof_schema_hash, GOLDEN_PROOF_SCHEMA_HASH);
    assert_eq!(manifest.refusal_code_set_hash, GOLDEN_REFUSAL_CODE_SET_HASH);
}

// ── Version check ─────────────────────────────────────────────────────────────

/// POSTCAD_PROTOCOL_VERSION is locked at "1.0" for the v1 pilot.
#[test]
fn protocol_version_constant_is_1_0() {
    assert_eq!(POSTCAD_PROTOCOL_VERSION, "1.0");
}

// ── Verification rejects protocol mismatch ───────────────────────────────────

/// verify_protocol_version must return protocol_version_mismatch when the
/// supplied version does not match POSTCAD_PROTOCOL_VERSION.
#[test]
fn verification_rejects_protocol_mismatch() {
    let err = VerificationFailure::protocol_version_mismatch("2.0", POSTCAD_PROTOCOL_VERSION);
    assert_eq!(err.code, "protocol_version_mismatch");
    assert!(
        err.message.contains("2.0"),
        "message should include the mismatched version"
    );
    assert!(
        err.message.contains(POSTCAD_PROTOCOL_VERSION),
        "message should include the expected version"
    );
    // A matching version must not produce an error (sanity).
    let ok = VerificationFailure::protocol_version_mismatch(
        POSTCAD_PROTOCOL_VERSION,
        POSTCAD_PROTOCOL_VERSION,
    );
    // The factory always creates the struct; caller decides when to raise it.
    // We just verify the code is stable.
    assert_eq!(ok.code, "protocol_version_mismatch");
}

// ── Verification rejects unknown refusal code ────────────────────────────────

/// is_known_refusal_code must return false for strings not in REFUSAL_CODES,
/// and VerificationFailure::unknown_refusal_code must carry the stable code.
#[test]
fn verification_rejects_unknown_refusal_code() {
    // Unknown codes.
    assert!(!is_known_refusal_code("totally_made_up_code"));
    assert!(!is_known_refusal_code(""));
    assert!(!is_known_refusal_code("NO_ELIGIBLE_MANUFACTURERS")); // wrong case

    // All canonical codes must be recognised.
    for code in REFUSAL_CODES {
        assert!(
            is_known_refusal_code(code),
            "canonical refusal code {:?} must be recognised",
            code
        );
    }

    // VerificationFailure factory for unknown codes.
    let err = VerificationFailure::unknown_refusal_code("totally_made_up_code");
    assert_eq!(err.code, "unknown_refusal_code");
    assert!(err.message.contains("totally_made_up_code"));
}

// ── Refusal code set completeness ────────────────────────────────────────────

/// REFUSAL_CODES must be sorted alphabetically and contain no duplicates.
#[test]
fn refusal_codes_are_sorted_and_unique() {
    let codes: Vec<&str> = REFUSAL_CODES.to_vec();
    let mut sorted = codes.clone();
    sorted.sort_unstable();
    assert_eq!(codes, sorted, "REFUSAL_CODES must be in alphabetical order");

    let mut deduped = codes.clone();
    deduped.dedup();
    assert_eq!(codes, deduped, "REFUSAL_CODES must contain no duplicates");
}
