//! Public receipt contract for the `route-case` CLI command.
//!
//! This module defines the stable, external output schema. It has no dependency
//! on internal routing or audit domain types. Any change here is a breaking
//! change to the CLI surface; internal refactors that do not affect receipt
//! fields should not require touching this file.

use serde::{Deserialize, Serialize};

/// The only schema version currently accepted by the routing and verification pipeline.
pub const RECEIPT_SCHEMA_VERSION: &str = "1";

/// Stable, verification-ready routing receipt emitted by `route-case`.
///
/// Both routed and refused outcomes share the same top-level schema.
/// `selected_candidate_id` is `null` for refused outcomes; `refusal_code` is
/// `null` for routed outcomes. The optional `refusal` section is omitted from
/// serialized JSON when absent (routed outcome).
///
/// All hash fields are lowercase hex SHA-256 digests (64 characters).
///
/// Audit chain fields (`audit_seq`, `audit_entry_hash`, `audit_previous_hash`)
/// allow consumers to anchor this receipt to an append-only audit log. The
/// entry hash is SHA-256 of `{seq, event, previous_hash}` and is independently
/// verifiable without access to the routing engine.
#[derive(Debug, Serialize, Deserialize, PartialEq)]
pub struct RoutingReceipt {
    /// Schema version of this receipt. Always `"1"` for receipts generated by
    /// the current pipeline. Verified before semantic checks during `verify-receipt`.
    pub schema_version: String,
    /// `"routed"` or `"refused"`.
    pub outcome: String,
    /// SHA-256 of the canonical case payload.
    pub case_fingerprint: String,
    /// SHA-256 of the canonical policy configuration.
    pub policy_fingerprint: String,
    /// Explicit policy/ruleset version label supplied by the policy bundle
    /// (e.g. `"v1"`, `"2024-01"`). `null` when no version was declared.
    ///
    /// Committed into [`routing_proof_hash`] via the
    /// `RoutingDecisionFingerprint`; verification fails if the version
    /// recorded here differs from the version in the policy bundle supplied
    /// to `verify-receipt`.
    pub policy_version: Option<String>,
    /// SHA-256 of the canonical routing decision fingerprint.
    pub routing_proof_hash: String,
    /// SHA-256 of the canonical registry snapshot committed at routing time.
    ///
    /// Computed from the full set of [`ManufacturerComplianceSnapshot`] items
    /// presented to the compliance gate, sorted by `manufacturer_id` before
    /// hashing. Any change to the registry data (eligibility flags, evidence
    /// references, attestation statuses) produces a different value and causes
    /// verification to fail via the [`routing_proof_hash`] check.
    pub registry_snapshot_hash: String,
    /// SHA-256 of the canonical candidate pool committed at routing time.
    ///
    /// Computed from the full input candidate universe (before policy filtering
    /// or compliance selection) via [`candidate_snapshot::hash_candidate_pool`].
    /// Candidates are sorted by `id` before hashing, so the value is
    /// order-independent with respect to the input slice.
    pub candidate_pool_hash: String,
    /// SHA-256 of the sorted eligible candidate ID list after compliance and
    /// policy filtering.
    ///
    /// Computed from `decision_trace.eligible_candidate_ids` — the candidates
    /// that survived both the compliance gate and the routing policy filter —
    /// via [`candidate_snapshot::hash_eligible_ids`]. IDs are sorted in
    /// ascending lexicographic order before hashing, so the value is
    /// order-independent.
    pub eligible_candidate_ids_hash: String,
    /// SHA-256 of the ordered selector-input candidate ID list.
    ///
    /// Computed from `decision_trace.eligible_candidate_ids` in the exact order
    /// they were presented to the deterministic selector — that is, the order
    /// produced by the compliance and policy filter chain without any additional
    /// sorting. Unlike [`eligible_candidate_ids_hash`], this hash is
    /// **order-sensitive**: the same IDs in a different order produce a
    /// different hash. Any reordering of the selector input is therefore
    /// detectable during verification.
    pub selection_input_candidate_ids_hash: String,
    /// ID of the selected routing candidate. `null` when refused.
    pub selected_candidate_id: Option<String>,
    /// Machine-readable refusal code. `null` when routed.
    pub refusal_code: Option<String>,
    /// Sequence number of this entry in the audit log.
    pub audit_seq: u64,
    /// SHA-256 of `{audit_seq, event, audit_previous_hash}`.
    pub audit_entry_hash: String,
    /// Hash of the preceding audit entry (genesis zeros for the first entry).
    pub audit_previous_hash: String,
    /// Detailed refusal context. Present only when `outcome == "refused"`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub refusal: Option<RefusalDetail>,
    /// SHA-256 of the canonical receipt content (all fields above, excluding
    /// this field itself). Computed last during generation and validated first
    /// during verification (after schema_version). Provides artifact-level
    /// tamper-evidence independent of any individual field hash.
    pub receipt_hash: String,
}

/// Result of verifying a routing receipt against the original inputs.
///
/// `result` is `"valid"` when the recomputed receipt matches the provided one
/// field-for-field. `"mismatch"` when one or more fields differ; the
/// `mismatched_fields` array lists every field name that did not match.
#[derive(Debug, Serialize, PartialEq)]
pub struct ReceiptVerificationResult {
    /// `"valid"` or `"mismatch"`.
    pub result: String,
    /// Field names that differed. Absent when `result == "valid"`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mismatched_fields: Option<Vec<String>>,
}

/// Detailed context for a refused routing outcome.
///
/// Present only when `outcome == "refused"`. Identifies which compliance or
/// policy constraint was not met and which candidate IDs were evaluated.
#[derive(Debug, Serialize, Deserialize, PartialEq)]
pub struct RefusalDetail {
    /// Human-readable explanation of the refusal.
    pub message: String,
    /// All candidate IDs that were evaluated before the refusal was issued.
    pub evaluated_candidate_ids: Vec<String>,
    /// The specific constraint gate that rejected the case.
    /// Stable values: `"compliance_gate"`, `"routing_policy"`,
    /// `"no_input_candidates"`, `"case_validation"`, `"unknown"`.
    pub failed_constraint: String,
}
